### ISSUE TITLE
Adding subprocess as triggeredByEvent="true"

### ISSUE THREAD

**Issue by hakanseysane** [bzinchenko/bpmnview#10]
Hello,

how do I add a subprocess as triggeredByEvent attribute is true?

**Comment by bzinchenko** [comment]
You can read rules for this on page 416 of official BPMN specification by OMG.

**Comment by hakanseysane** [comment]
Thank you sir.

I read rules from official BPMN specification but I don't understand how to add a subprocess as triggeredByEvent is true or isExpanded is true.

**Comment by bzinchenko** [comment]
According to specification, we ve made it as follows:

`if ((activityType == ActivityType.Process || activityType == ActivityType.EventSubProcess) && (marker & ActivityMarker.Collapsed) != 0)) subProc.triggeredByEvent.Value = false;`

We hope it clarifies. If you see it contradicting to specification, please let us know.

**Comment by bzinchenko** [comment]
`isExpanded` is a property of **shape**, not of a process. Please inspect shape properties for relevant field.
