### ISSUE TITLE
How can I add an Annotation - _editor.AddAnnotation(...) returns null instead of an guid

### ISSUE THREAD

**Issue by FS-FIT** [bzinchenko/bpmnview#18]
Hello,
thanks for your really good work :-)

We are trying to add an annotation to an activity with the no result. We can not find any xml <semantic:textAnnotation> ...  element in the bpmn file for the annotation. 

The _editor.AddAnnotation(...) returns null instead of an guid. 

The activity for example is working well.

Can anyone of you give us an hint?

Thanks :-)

1. We are adding the Activity and store the id of the activity in an variable

  _bpmnElementID = AddActivity(bpmn);
 shape.ElementRef = _bpmnElementID;
_editor.AddShape(bpmnRootID, shape);

  public string AddActivity(BpmnObject o)
        {
            return _editor.AddActivity(null, o.Name, o.ActivityType, o.ActivityMarker,    o.TaskType, o.CalledElement);
           
        }

2. After that we are trying to add the annotation with to the activity with the ID _bpmnElementID.

  string annotationID = AddAnnotation(_bpmnElementID, bpmn.Annotation, true);
 shape.ElementRef = annotationID;
 _editor.AddShape(bpmnRootID, shape);

  public string AddAnnotation(string bpmnID, string text, bool rightAlign)
        {
            return _editor.AddAnnotation(bpmnID, text,rightAlign);
        }

**Comment by bzinchenko** [comment]
Hello
Annotation is possible add to process or collaboration. Pass proper ID of process or collaboration to the function and annotation will be added properly. It is not possible to add annotation to element. Please refer to BPMN specification for further details.

**Comment by FS-FIT** [comment]
Hello,
thanks for your reply. According to the specification and according to Bruce Silver (he was development member from BPMN 2.0 of OMG) can the Text Annotation be used to include addition information to flow objects (Activities, Gateways and Events). 

So can you please add the possibility to add annotation for any  flow objects? 

This will really help us to describe our process in more detail with comments.

One Example:
<img width="939" alt="image" src="https://user-images.githubusercontent.com/47035321/73430028-4b15b000-433d-11ea-91f2-68d7afa3ecff.png">

Thanks and kind regards

**Comment by bzinchenko** [comment]
Hello
You mix business logic with visual appearance of diagram.
1. Annotation is possible add ONLY to process or collaboration according to BPMN specs. 
2. Annotation is possible to point to ANY diagram element through appropriate edge.
Assign proper coordinates of end point to have annotation pointing to relevant shape.
