### ISSUE TITLE
BPMN.Model.Read(fileName) method overloads ?

### ISSUE THREAD

**Issue by guilmori** [bzinchenko/bpmnview#2]
The method BPMN.Model.Read(fileName) has only one overload taking a filename as input.

My BPMN files may be in a database or on azure storage.
So now I'm forced to write file on disk to be able to load them.

**Comment by bzinchenko** [comment]
Correct observation. We already noticed this inconvenience ourselves will add new method to load XML from string. It will be included into next version.

**Comment by bzinchenko** [comment]
I added function:

    public static Model Parse(string xml);

To get model directly from XML string. 

Exact date for this update is not clear yet because all project undergoes major extensions to enable creating and writing BPMN models, not only rendering pictures as now. Existing methods and interfaces will not be affected.

**Comment by guilmori** [comment]
I would love if you could make a release including only that small changes.
Thanks !

**Comment by bzinchenko** [comment]
This issue is resolved with the update to new version of BPMN.Sharp 1.0.6
