### ISSUE TITLE
BPMN.Model.Read source code ?

### ISSUE THREAD

**Issue by Diaskhan** [bzinchenko/bpmnview#4]
Can U provide 
BPMN.Model.Read source code.

I'am trying to do bpmn file parsing with standart XmlDocument.
But I could'nt do it, maybe in source code BPMN.Model.Read have some explanation how to do it !

**Comment by bzinchenko** [comment]
You can validate XML document by many free checkers with detailed report on possible errors. For instance, use this: https://www.businessprocessincubator.com/cloudapps/#web-service-221

**Comment by Diaskhan** [comment]
Sorry, but wont need to validate bpmn files.
I want to read bpmn file. Searching workable solution with source code !
Could U explain how do U read and parse bpmn files ???
