### ISSUE TITLE
Could U sell BPMN.Sharp library source code.

### ISSUE THREAD

**Issue by Diaskhan** [bzinchenko/bpmnview#5]
Could U sell BPMN.Sharp library source code.

**And how much it cost ???**

**Comment by bzinchenko** [comment]
BPMN.Sharp is another project separate from BPMN View. BPMN.Sharp library is freely available from NuGet under loyal MIT license suitable for personal and commercial usage. Access to source code of BPMN.Sharp is negotiable as a part of large enterprise projects. It is not offered standalone.
