### ISSUE TITLE
Adding Subprocess and its child items

### ISSUE THREAD

**Issue by hakanseysane** [bzinchenko/bpmnview#9]
I adding subprocess like:

editor.AddActivity(null, "SUBPROCESS", ActivityType.EventSubProcess, ActivityMarker.None, TaskType.None, null);

How do I add child items of this subprocess?

**Comment by bzinchenko** [comment]
Hello

Very simple. AddActivity() returns ID of newly created activity. If you created a sub-process, the ID will be the ID of created sub-process. Pass this ID as a first argument to any other Add....() function, which all expect process or sub-process ID as their first argument. Respective elements will be added properly to your sub-process. For instance:

```
string ID = editor.AddActivity(null, "SUBPROCESS", ActivityType.EventSubProcess, ActivityMarker.None, TaskType.None, null);
editor.AddActivity(ID, "SUBPROCESS", ActivityType.EventSubProcess, ActivityMarker.None, TaskType.None, null);
```
creates a nested sub-process inside a sub-process.
